import type { Metadata } from "next";
import "./globals.css";
import { bitcount, doublePivot, geistMono, geistSans, pressStart2P, wireOne } from "./fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${bitcount.variable} ${pressStart2P.variable} ${wireOne.variable} ${doublePivot.variable}`}
      >
        {children}
      </body>
    </html>
  );
}
